local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.api.nvim_create_user_command("HarpoonMenu", ui.toggle_quick_menu, {})

vim.keymap.set("n", "<leader>a", mark.add_file, { desc = "harpoon: mark file" })
vim.keymap.set("n", "<leader>m", ui.toggle_quick_menu, { desc = "harpoon: open menu" })

vim.keymap.set("n", "<leader>h", function()
	ui.nav_file(1)
end, { desc = "harpoon: goto mark 1" })
vim.keymap.set("n", "<leader>j", function()
	ui.nav_file(2)
end, { desc = "harpoon: goto mark 2" })
vim.keymap.set("n", "<leader>k", function()
	ui.nav_file(3)
end, { desc = "harpoon: goto mark 3" })
vim.keymap.set("n", "<leader>l", function()
	ui.nav_file(4)
end, { desc = "harpoon: goto mark 4" })
